# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch('DATABASE_POSTGRESQL_USERNAME') { 'postgres' } %>
  password: <%= ENV.fetch('DATABASE_POSTGRESQL_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DATABASE_POSTGRESQL_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_POSTGRESQL_PORT') { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tasks_api_development

test:
  <<: *default
  database: tasks_api_test

production:
  <<: *default
  database: tasks_api_production